#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-pack-flash'

# Update alternatives
update-alternatives --quiet --remove \
  flash-mozilla.so \
  /usr/lib/custom-pack-flash/npapi/libflashplayer.so

# Exit
exit 0

