#!/bin/sh
## CUSTOM-CONF: File automatically created/updated [custom-conf-docker]

# (Please use 'dpkg-reconfigure custom-conf-docker' to change this setting)
%{CUSTOM_CONF_DOCKER_IPTABLES_AUTO_EXIT}


## Docker-specific rules

# Drop and log inbound traffic (to host or default Docker bridge services)
"${IPTABLES}" --table filter --append INPUT --in-interface docker1 --jump BLACKLIST_DROP
"${IPTABLES}" --table filter --append FORWARD --in-interface docker1 --out-interface docker0 --jump BLACKLIST_DROP
# (Please use a separate file to add exceptions)

# Inbound traffic (to containers published ports)
"${IPTABLES}" --table filter --new-chain DOCKER1_INBOUND
"${IPTABLES}" --table filter --append FORWARD ! --in-interface docker1 --out-interface docker1 --jump DOCKER1_INBOUND
# (Please use a separate file to add containers-specific rules)
# "${IPTABLES}" --table filter --append DOCKER1_INBOUND \
#   ! --in-interface docker1 \
#     --out-interface docker1 \
#     --destination <ip> \
#     --protocol <proto> \
#     --dport <port> \
#     --jump ACCEPT

# Outbound traffic (from containers to the wide wild world)
"${IPTABLES}" --table filter --new-chain DOCKER1_OUTBOUND
"${IPTABLES}" --table filter --append FORWARD --in-interface docker1 ! --out-interface docker1 --jump DOCKER1_OUTBOUND
"${IPTABLES}" --table filter --append DOCKER1_OUTBOUND --jump ACCEPT

# Internal traffic (between containers)
modprobe br_netfilter 2>/dev/null
"${IPTABLES}" --table filter --new-chain DOCKER1_INTERNAL
"${IPTABLES}" --table filter --append FORWARD --in-interface docker1 --out-interface docker1 --jump DOCKER1_INTERNAL
"${IPTABLES}" --table filter --append DOCKER1_INTERNAL --jump ACCEPT

