#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-symfony'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Add dedicated user (for composer usage)
adduser --system --home /opt/symfony --no-create-home --shell /bin/false --gecos 'PHP/Symfony Framework' --disabled-login symfony

# Fine-tune permissions
chmod 0640 /etc/php/symfony/parameters.yml
chown root:www-data /etc/php/symfony/parameters.yml
chmod 2370 /var/log/php/symfony
chown www-data:adm /var/log/php/symfony
chmod 2350 /var/cache/php/symfony
chown www-data:www-data /var/cache/php/symfony
[ ! -g /opt/symfony-3.4 ] && find /opt/symfony-3.4 -type d -exec chmod g+s {} \;
[ "$(stat -c '%U' /opt/symfony-3.4)" != 'symfony' ] && chown -R symfony:nogroup /opt/symfony-3.4

# Fine-tune configuration
if fgrep -q '%{CUSTOM_CONF_SYMFONY_SECRET}' /etc/php/symfony/parameters.yml; then
  echo "NOTICE[${PKGNAME}]: Generating secret token; this may take some time..."
  CUSTOM_CONF_SYMFONY_SECRET="$(dd if=/dev/random bs=512 count=1 2>/dev/null | sha1sum | awk '{print $1}')"
  gcfg.sed "s|%{CUSTOM_CONF_SYMFONY_SECRET}|${CUSTOM_CONF_SYMFONY_SECRET}|" /etc/php/symfony/parameters.yml
fi

# Additional actions
(
  set -e
  pushd /opt/symfony >/dev/null
  trap 'popd >/dev/null' EXIT
  /usr/bin/php /usr/share/custom-conf-symfony/composer.phar self-update
)
cat << EOF
NOTICE[${PKGNAME}]: You must now install/update the Symfony framework MANUALLY; please...
: symfony-composer install
: symfony-composer update
NOTICE[${PKGNAME}]: If upgrading an existing installation, please...
: rm -rf /var/cache/php/symfony/*
: service apache2 restart

EOF

# Exit
exit 0

