#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-apt'

# Debconf
. /usr/share/debconf/confmodule
# ... preseed
for var_priority in debian-multimedia:high debian-backports:high; do
  var="${var_priority%:*}"
  priority="${var_priority#*:}"
  db_input ${priority} ${PKGNAME}/${var}
  db_go
done
# ... get
db_get custom-conf/host-type && HOST_TYPE="${RET}"
db_get ${PKGNAME}/debian-multimedia && DEB_MULTIMEDIA="${RET}"
db_get ${PKGNAME}/debian-backports && DEB_BACKPORTS="${RET}"
db_stop

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Fine-tune files
case "${HOST_TYPE}" in
  workstation|computation|laptop) ENABLE_APT_UPDATE_CHECK=false;;
  server|vserver) ENABLE_APT_UPDATE_CHECK=true;;
  *)
    echo "WARNING[${PKGNAME}]: Unsupported host type (${HOST_TYPE})";
    ENABLE_APT_UPDATE_CHECK=false
    ;;
esac
gcfg.sed "s|%{ENABLE_APT_UPDATE_CHECK}|${ENABLE_APT_UPDATE_CHECK}|g" /etc/cron.d/apt-update-check
[ "${DEB_MULTIMEDIA}" == 'true' ] && gcfg.sed "s|^#deb |deb |" /etc/apt/sources.list.d/debian-multimedia.list
[ "${DEB_BACKPORTS}" == 'true' ] && gcfg.sed "s|^#deb |deb |" /etc/apt/sources.list.d/debian-backports.list

# Uninstall deprecated GPG keys
#if [ -x /usr/bin/apt-key ]; then
#  #/usr/bin/apt-key del <fingerprint>
#fi

# Exit
exit 0

