#!/bin/bash


## Usage
function _help {
  cat << EOF
USAGE: ${0##*/}

SYNOPSIS:
  Set (start) IPv6 tables (firewall) rules gracefully.
EOF
}


## Actions
[ "${1##*-}" == 'help' ] && _help && exit 1
[ -n "${ADDRFAM}" -a "${ADDRFAM}" != 'inet6' ] && exit 0
[ -e /var/lock/ip6tables.lock ] && exit 0
/usr/share/custom-conf-iptables/scripts/ip6tables-control start

