#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-udev'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Additional actions
udevadm trigger

# Exit
exit 0

