#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-network-bond'

# Debconf
. /usr/share/debconf/confmodule
# ... preseed
for var_priority in bond-name:high bond-mode:high bond-slaves:high bond-primary:high; do
  var="${var_priority%:*}"
  priority="${var_priority#*:}"
  db_input ${priority} ${PKGNAME}/${var}
  db_go
done
# ... get
db_get ${PKGNAME}/bond-name && CUSTOM_CONF_NETWORK_BOND="${RET}"
db_get ${PKGNAME}/bond-mode && CUSTOM_CONF_NETWORK_BOND_MODE="${RET}"
db_get ${PKGNAME}/bond-slaves && CUSTOM_CONF_NETWORK_BOND_SLAVES="${RET}"
db_get ${PKGNAME}/bond-primary && CUSTOM_CONF_NETWORK_BOND_PRIMARY="${RET}"
db_stop

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1


## Fine-tuning

# Retrieve network settings
# ... retrieve default gateway
CUSTOM_CONF_NETWORK_DFLTGW="$(ip -6 route | grep '^default' | head -n 1)"
[ -z "${CUSTOM_CONF_NETWORK_DFLTGW}" ] && CUSTOM_CONF_NETWORK_DFLTGW="$(ip -4 route | grep '^default' | head -n 1)"
[ -z "${CUSTOM_CONF_NETWORK_DFLTGW}" ] && echo 'ERROR: Failed to retrieve the default gateway' >&2 && exit 1
# ... retrieve default gateway interface
CUSTOM_CONF_NETWORK_DEVICE="$(echo "${CUSTOM_CONF_NETWORK_DFLTGW}" | fgrep ' dev ' | sed 's|^.* dev \([^ ]*\)\( .*\)*$|\1|')"
[ -z "${CUSTOM_CONF_NETWORK_DEVICE}" ] && echo 'ERROR: Failed to retrieve the main interface' >&2 && exit 1
# ... retrieve default gateway IP addresses
CUSTOM_CONF_NETWORK_IP4GATEWAY="$(ip -4 route | grep '^default' | head -n 1 | sed 's|^.* via \([^ ]*\) dev .*$|\1|')"
[ -z "${CUSTOM_CONF_NETWORK_IP4GATEWAY}" ] && echo 'ERROR: Failed to retrieve the gateway IPv4 address' >&2 && exit 1
CUSTOM_CONF_NETWORK_IP6GATEWAY="$(ip -6 route | grep '^default' | head -n 1 | sed 's|^.* via \([^ ]*\) dev .*$|\1|')"
[ -z "${CUSTOM_CONF_NETWORK_IP6GATEWAY}" ] && echo 'ERROR: Failed to retrieve the gateway IPv6 address' >&2 && exit 1
# ... retrieve IP addresses
CUSTOM_CONF_NETWORK_IP4ADDRESS="$(ip -4 addr show ${CUSTOM_CONF_NETWORK_DEVICE} | fgrep ' scope global ' | head -n 1 | sed 's|^.*inet \([^ /]*\)\(/[^ ]*\)*\( .*\)*$|\1|')"
CUSTOM_CONF_NETWORK_IP6ADDRESS="$(ip -6 addr show ${CUSTOM_CONF_NETWORK_DEVICE} | fgrep ' scope global ' | head -n 1 | sed 's|^.*inet6 \([^ /]*\)\(/[^ ]*\)*\( .*\)*$|\1|')"
# ... retrieve network masks
CUSTOM_CONF_NETWORK_IP4MASK="$(ip -4 addr show ${CUSTOM_CONF_NETWORK_DEVICE} | fgrep ' scope global ' | head -n 1 | sed 's|^.*inet \([^ /]*\)/\([^ ]*\)\( .*\)*$|\2|')"
CUSTOM_CONF_NETWORK_IP6MASK="$(ip -6 addr show ${CUSTOM_CONF_NETWORK_DEVICE} | fgrep ' scope global ' | head -n 1 | sed 's|^.*inet6 \([^ /]*\)/\([^ ]*\)\( .*\)*$|\2|')"

# Configure network interface
[ -z "${CUSTOM_CONF_NETWORK_BOND}" ] && CUSTOM_CONF_NETWORK_BOND='bond0'
[ -z "${CUSTOM_CONF_NETWORK_BOND_MODE}" ] && CUSTOM_CONF_NETWORK_BOND_MODE='#bond-mode N/A' || CUSTOM_CONF_NETWORK_BOND_MODE="bond-mode ${CUSTOM_CONF_NETWORK_BOND_MODE}"
[ -z "${CUSTOM_CONF_NETWORK_BOND_SLAVES}" ] && CUSTOM_CONF_NETWORK_BOND_SLAVES='#bond-slaves N/A' || CUSTOM_CONF_NETWORK_BOND_SLAVES="bond-slaves ${CUSTOM_CONF_NETWORK_BOND_SLAVES}"
[ -z "${CUSTOM_CONF_NETWORK_BOND_PRIMARY}" ] && CUSTOM_CONF_NETWORK_BOND_PRIMARY='#bond-primary N/A' || CUSTOM_CONF_NETWORK_BOND_PRIMARY="bond-primary ${CUSTOM_CONF_NETWORK_BOND_PRIMARY}"
gsed "s|%{CUSTOM_CONF_NETWORK_BOND}|${CUSTOM_CONF_NETWORK_BOND}|g;s|%{CUSTOM_CONF_NETWORK_BOND_MODE}|${CUSTOM_CONF_NETWORK_BOND_MODE}|g;s|%{CUSTOM_CONF_NETWORK_BOND_SLAVES}|${CUSTOM_CONF_NETWORK_BOND_SLAVES}|g;s|%{CUSTOM_CONF_NETWORK_BOND_PRIMARY}|${CUSTOM_CONF_NETWORK_BOND_PRIMARY}|g;s|%{CUSTOM_CONF_NETWORK_IP4ADDRESS}|${CUSTOM_CONF_NETWORK_IP4ADDRESS}|g;s|%{CUSTOM_CONF_NETWORK_IP4MASK}|${CUSTOM_CONF_NETWORK_IP4MASK}|g;s|%{CUSTOM_CONF_NETWORK_IP4GATEWAY}|${CUSTOM_CONF_NETWORK_IP4GATEWAY}|g;s|%{CUSTOM_CONF_NETWORK_IP6ADDRESS}|${CUSTOM_CONF_NETWORK_IP6ADDRESS}|g;s|%{CUSTOM_CONF_NETWORK_IP6MASK}|${CUSTOM_CONF_NETWORK_IP6MASK}|g;s|%{CUSTOM_CONF_NETWORK_IP6GATEWAY}|${CUSTOM_CONF_NETWORK_IP6GATEWAY}|g" /etc/network/interfaces

# Warning
echo "WARNING[${PKGNAME}]: You MUST reboot to enforce configuration changes!"

# Exit
exit 0

