#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-php84-apache2'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Fine-tune configuration
source /usr/share/custom-conf/custom-conf.defs
CUSTOM_CONF_ETC_TIMEZONE="$(head -n 1 /etc/timezone)"
gcfg.sed "s|%{CUSTOM_CONF_SMTP_SERVER}|${CUSTOM_CONF_SMTP_SERVER}|g;s|%{CUSTOM_CONF_ETC_TIMEZONE}|${CUSTOM_CONF_ETC_TIMEZONE}|g" /etc/php/8.4/apache2/php.ini
# ... logrotate
CUSTOM_CONF_PHP84_APACHE2_LOGOWNER='root'
[ "$(lsb_release -si)" == 'Ubuntu' ] && CUSTOM_CONF_PHP84_APACHE2_LOGOWNER='syslog'
gcfg.sed "s|%{CUSTOM_CONF_PHP84_APACHE2_LOGOWNER}|${CUSTOM_CONF_PHP84_APACHE2_LOGOWNER}|g" /etc/logrotate.d/php84-apache2-rsyslog

# Fine-tune permissions
chmod 350 /var/log/php/8.4
chown www-data:adm /var/log/php/8.4

# Additional actions
invoke-rc.d apache2 restart

# Exit
exit 0
