#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-hostname-dhcp'

# TRANSITIONAL
[ -e /etc/rc.local.d/10-hostname ] && gcfg move --batch /etc/rc.local.d/10-hostname /etc/rc.local.d/10-custom-conf-hostname-dhcp

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Debhelpers
#DEBHELPER#

# Exit
exit 0

