#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-hostname-dhcp'

# TRANSITIONAL
[ -e /etc/rc.local.d/10-hostname ] && gcfg move --batch /etc/rc.local.d/10-hostname /etc/rc.local.d/10-custom-conf-hostname-dhcp
[ -e /etc/rc.local.d/10-custom-conf-hostname-dhcp ] && ! gcfg flagged /etc/rc.local.d/10-custom-conf-hostname-dhcp @EDITED && gcfg remove --batch /etc/rc.local.d/10-custom-conf-hostname-dhcp

# Debhelpers
#DEBHELPER#

# Exit
exit 0

