#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-ha]

# Usage
[ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/} <constraint-id>

HINT: cibadmin -o constraints -D -A "//rsc_location[@id='\${constraint-id}']"
EOF

# Command
HA_RID="$1"
cibadmin -o constraints -D -A "//rsc_location[@id='${HA_RID}']"

