#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-ha]

# Usage
[ "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/}

HINT: crm_attribute -n maintenance-mode -D
EOF

# Command
crm_attribute -n maintenance-mode -D

