#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-ha]

# Usage
[ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/} <node>

HINT: crm_standby -N <node> -v true
EOF

# Command
HA_NODE="$1"
crm_standby -N "${HA_NODE}" -v true

