#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-ha]

# Usage
[ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/} <ALL|resource-id> [<node>]

HINT: crm_resource -r <resource-id> -H <node> -C

$(crm_mon  -1 | fgrep -i -A 1000 'Failed actions' | sed 's/^\s*\(.*-[^_]*\)_[^ ]* \((node=\|on \)\([^, ]*\)[, ].*/\1 \3/')
EOF

# Command
HA_RID="$1"
HA_NODE="$2"
if [ "${HA_RID}" == 'ALL' ]; then
  i=0; crm_mon  -1 | fgrep -i -A 1000 'Failed actions' | grep '[^ ]-[^ ]*_[^ ]* \(node=\|on \)' | sed 's/^\**\s*\(.*-[^_]*\)_[^ ]* \((node=\|on \)\([^, ]*\)[, ].*/\1 \3/' | while read HA_RID HA_NODE; do
    [ ${i} -gt 0 ] && sleep 10
    crm_resource -r "${HA_RID}" -H "${HA_NODE}" -C
    let i+=1
  done
else
  [ -z "${HA_NODE}" ] && echo 'ERROR: Missing node specification' >&2 && exit 1
  crm_resource -r "${HA_RID}" -H "${HA_NODE}" -C
fi

