#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-ha]

# Usage
[ "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/}

HINT: crm_attribute -t rsc_defaults -n resource-stickiness -D
HELP: crm_attribute --help
EOF

# Command
crm_attribute -t rsc_defaults -n resource-stickiness -D

