#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-apache2-templates'

# Retrieve Apache version
CUSTOM_CONF_APACHE2_VERSION="$(apachectl -v | fgrep 'Apache/2' | sed 's/^.*Apache\/\([0-9]*\).\([0-9]*\).*$/\1.\2/')"
case "${CUSTOM_CONF_APACHE2_VERSION}" in
  '2.2'|'2.4')
    echo "INFO[${PKGNAME}]: Detected supported Apache version (${CUSTOM_CONF_APACHE2_VERSION})"
    ;;
  *)
    echo "ERROR[${PKGNAME}]: Unsupported Apache version (${CUSTOM_CONF_APACHE2_VERSION})"
    exit 1
    ;;
esac

# Configuration upgrade
if [ -e /usr/share/${PKGNAME}/upgrade-config.apache-${CUSTOM_CONF_APACHE2_VERSION} ]; then
  /usr/share/${PKGNAME}/upgrade-config.apache-${CUSTOM_CONF_APACHE2_VERSION} detect && cat << EOF && exit 0
WARNING[${PKGNAME}]: Old Apache configuration detected! Please upgrade and re-configure.
: /usr/share/${PKGNAME}/upgrade-config.apache-${CUSTOM_CONF_APACHE2_VERSION}
: dpkg-reconfigure ${PKGNAME}
EOF
fi

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config/apache-${CUSTOM_CONF_APACHE2_VERSION}" || exit 1

# Fix permissions
find /etc/apache2/htpasswd -type f -exec chown root:www-data {} \; -exec chmod 640 {} \;
case "${CUSTOM_CONF_APACHE2_VERSION}" in
  '2.2')
    chown root:root /etc/apache2/sites-available/default-auth
    chmod 640 /etc/apache2/sites-available/default-auth
    ;;
  '2.4')
    chown root:root /etc/apache2/sites-available/default-auth.conf
    chmod 640 /etc/apache2/sites-available/default-auth.conf
    ;;
esac

# Additional actions
invoke-rc.d apache2 restart

# Exit
exit 0

