#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-conf-postgresql'

# Retrieve PostgreSQL version
CUSTOM_CONF_POSTGRESQL_VERSION='unsupported'
for version in 9.{9..0}; do
  [ -e /usr/lib/postgresql/${version}/bin/initdb ] && CUSTOM_CONF_POSTGRESQL_VERSION=${version} && break
done
case "${CUSTOM_CONF_POSTGRESQL_VERSION}" in
  '9.1'|'9.4'|'9.6')
    echo "INFO[${PKGNAME}]: Detected supported PostgreSQL version (${CUSTOM_CONF_POSTGRESQL_VERSION})"
    ;;
  *)
    echo "ERROR[${PKGNAME}]: Unsupported PostgreSQL version (${CUSTOM_CONF_POSTGRESQL_VERSION})"
    exit 1
    ;;
esac

# Uninstall files
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config/postgresql-${CUSTOM_CONF_POSTGRESQL_VERSION}" || exit 1

# Exit
exit 0

