#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-nfs4'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Use Kerberos/RPCSEC-GSS ?
CUSTOM_CONF_NFS4_GSSD=
[ -e /etc/krb5.keytab ] && CUSTOM_CONF_NFS4_GSSD='yes'

# Fine-tune configuration
source /usr/share/custom-conf/custom-conf.defs
gcfg.sed "s|%{CUSTOM_CONF_DOMAIN}|${CUSTOM_CONF_DOMAIN}|g" /etc/idmapd.conf
gcfg.sed "s|%{CUSTOM_CONF_NFS4_GSSD}|${CUSTOM_CONF_NFS4_GSSD}|g" /etc/default/nfs-common

# Additional actions
[ -h /var/lib/nfs/rpc_pipefs ] && rm /var/lib/nfs/rpc_pipefs  # clean-up legacy mess
sysctl --system
invoke-rc.d nfs-common restart
[ -z "${CUSTOM_CONF_NFS4_GSSD}" ] && pkill -x rpc.gssd

# Exit
exit 0

