#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-php73-apache2'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Fine-tune configuration
source /usr/share/custom-conf/custom-conf.defs
CUSTOM_CONF_ETC_TIMEZONE="$(head -n 1 /etc/timezone)"
gcfg.sed "s|%{CUSTOM_CONF_SMTP_SERVER}|${CUSTOM_CONF_SMTP_SERVER}|g;s|%{CUSTOM_CONF_ETC_TIMEZONE}|${CUSTOM_CONF_ETC_TIMEZONE}|g" /etc/php/7.3/apache2/php.ini
# ... logrotate
CUSTOM_CONF_PHP73_APACHE2_LOGOWNER='root'
[ "$(lsb_release -si)" == 'Ubuntu' ] && CUSTOM_CONF_PHP73_APACHE2_LOGOWNER='syslog'
CUSTOM_CONF_PHP73_APACHE2_LOGROTATE='invoke-rc.d rsyslog rotate >/dev/null'
[ "$(lsb_release -si)" == 'Debian' -a $(lsb_release -sr | cut -d. -f1) -lt 7 ] && CUSTOM_CONF_PHP73_APACHE2_LOGROTATE='invoke-rc.d rsyslog reload >/dev/null'
[ "$(lsb_release -si)" == 'Ubuntu' -a $(lsb_release -sr | cut -d. -f1) -lt 14 ] && CUSTOM_CONF_PHP73_APACHE2_LOGROTATE='reload rsyslog >/dev/null 2>\&1 \|\| true'
gcfg.sed "s|%{CUSTOM_CONF_PHP73_APACHE2_LOGOWNER}|${CUSTOM_CONF_PHP73_APACHE2_LOGOWNER}|g;s|%{CUSTOM_CONF_PHP73_APACHE2_LOGROTATE}|${CUSTOM_CONF_PHP73_APACHE2_LOGROTATE}|g" /etc/logrotate.d/php73-apache2-rsyslog

# Fine-tune permissions
chmod 350 /var/log/php/7.3
chown www-data:adm /var/log/php/7.3

# Additional actions
invoke-rc.d apache2 restart

# Exit
exit 0

