#!/bin/bash
## File automatically created/updated [nagios-plugins-custom]
# EXIT: 0 = OK; 1 = WARNING; 2 = CRITITCAL; 3 = UNKNOWN (ERROR)
# ECHO: <human-friendly status message> |<performance_data>

# Usage
[ $# -lt 2  -o "${1##*-}" == 'help' ] && cat << EOF && exit 3
USAGE: ${0##*/} <temp_celsius:warning> <temp_celsius:critical>
SYNOPSIS: Nagios-compliant command to check motherboard temperature
REQUIRED: lm-sensors (check: sensors)
EOF

# Arguments
TEMP_WARNING=$1
TEMP_CRITICAL=$2
# ... checks
which sensors >/dev/null
[ $? -ne 0 ] && echo 'ERROR: Missing sensors monitoring utility (sensors)' && exit 3
[ $(( ${TEMP_WARNING} <= 0 )) -ne 0 ] && echo 'ERROR: Warning threshold must be bigger than 0' && exit 3
[ $(( ${TEMP_CRITICAL} <= 0 )) -ne 0 ] && echo 'ERROR: Critical threshold must be bigger than 0' && exit 3
[ $(( ${TEMP_WARNING} > ${TEMP_CRITICAL} )) -ne 0 ] && echo 'ERROR: Warning threshold must be lower than critical threshold' && exit 3

# Sensor temperature
export LANG='en_US.UTF-8'  # Make sure non-ASCII characters (°) do not vanish from commands output
SENSOR_OUTPUT=$(sensors | egrep -i '(temp|°c)' | egrep -i '(board|m/?b)')
[ -z "${SENSOR_OUTPUT}" ] && echo 'ERROR: Missing motherboard temperature' && exit 3
SENSOR_TEMP=$(echo ${SENSOR_OUTPUT} | cut -d':' -f2 | sed 's/[^0-9]*\([0-9]*\).*/\1/g')
[ $(( ${SENSOR_TEMP} <= 0 )) -ne 0 ] && echo 'ERROR: Invalid motherboard temperature' && exit 3

# Check
[ $(( ${SENSOR_TEMP} / ${TEMP_CRITICAL} >= 1 )) -ne 0 ] && echo "CRITICAL: Motherboard temperature (${SENSOR_TEMP}C) is bigger than ${TEMP_CRITICAL}C |${SENSOR_TEMP},${TEMP_WARNING},${TEMP_CRITICAL},2" && exit 2
[ $(( ${SENSOR_TEMP} / ${TEMP_WARNING} >= 1 )) -ne 0 ] && echo "WARNING: Motherboard temperature (${SENSOR_TEMP}C) is bigger than ${TEMP_WARNING}C |${SENSOR_TEMP},${TEMP_WARNING},${TEMP_CRITICAL},1" && exit 1
echo "OK: Motherboard temperature (${SENSOR_TEMP}C) is within tolerance |${SENSOR_TEMP},${TEMP_WARNING},${TEMP_CRITICAL},0"

