#!/bin/bash
BASE='/opt/django-1.11'
COMMAND="${1}"; shift
OPTIONS="$@"
case "${COMMAND}" in
  'install')
    su -l django -s /bin/sh -c "PATH=${BASE}/bin PYTHONUSERBASE=${BASE} pip2 ${COMMAND} --user --no-cache --compile --requirement=/etc/python/django/requirements.txt ${OPTIONS}"
    ;;

  'list')
    su -l django -s /bin/sh -c "PATH=${BASE}/bin PYTHONUSERBASE=${BASE} pip2 ${COMMAND} --user ${OPTIONS}"
    ;;

  'show'|'uninstall')
    su -l django -s /bin/sh -c "PATH=${BASE}/bin PYTHONUSERBASE=${BASE} pip2 ${COMMAND} ${OPTIONS}"
    ;;

  *)
    echo "ERROR: Invalid/unsupported command (${COMMAND})" && exit 1
    ;;
esac

