#!/usr/bin/env php
<?php

set_time_limit(0);
require_once __DIR__.'/autoload.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$oInput = new ArgvInput();
$sEnvironment = $oInput->getParameterOption(array('--env', '-e'), PHP_SYMFONY_ENV);
$bDebug = PHP_SYMFONY_DEBUG && !$oInput->hasParameterOption(array('--no-debug', '')) && $sEnvironment !== 'prod';

if ($sEnvironment === 'dev') umask(0002);
if ($bDebug) Debug::enable();
$oKernel = new AppKernel($sEnvironment, $bDebug);
$oApplication = new Application($oKernel);
$oApplication->run($oInput);

