#!/bin/sh
## CUSTOM-CONF: File automatically created/updated [custom-conf-ssmtp]

# Reconfigure package after hostname DHCP update
DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical dpkg-reconfigure custom-conf-ssmtp

