#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-conf-django'

# Retrieve Django version
CUSTOM_CONF_DJANGO_VERSION="$(django-admin --version | sed 's/^\([0-9]*\).\([0-9]*\).*$/\1.\2/')"
case "${CUSTOM_CONF_DJANGO_VERSION}" in
  '1.4'|'1.7')
    echo "INFO[${PKGNAME}]: Detected supported Django version (${CUSTOM_CONF_DJANGO_VERSION})"
    ;;
  *)
    echo "ERROR[${PKGNAME}]: Unsupported Django version (${CUSTOM_CONF_DJANGO_VERSION})"
    exit 1
    ;;
esac

# Retrieve Apache version
CUSTOM_CONF_APACHE2_VERSION="$(apachectl -v | fgrep 'Apache/2' | sed 's/^.*Apache\/\([0-9]*\).\([0-9]*\).*$/\1.\2/')"
case "${CUSTOM_CONF_APACHE2_VERSION}" in
  '2.2'|'2.4')
    echo "INFO[${PKGNAME}]: Detected supported Apache version (${CUSTOM_CONF_APACHE2_VERSION})"
    ;;
  *)
    echo "ERROR[${PKGNAME}]: Unsupported Apache version (${CUSTOM_CONF_APACHE2_VERSION})"
    exit 1
    ;;
esac

# Uninstall files
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config/django${CUSTOM_CONF_DJANGO_VERSION}" >/dev/null || exit 1
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config/apache${CUSTOM_CONF_APACHE2_VERSION}" >/dev/null || exit 1
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config/common" || exit 1

# Exit
exit 0

