#!/bin/bash
## CUSTOM-CONF: File automatically created/updated [custom-conf-ipv6-dhcp]

# Usage
[ "${1##*-}" == 'help' ] && cat << EOF && exit 1
USAGE: ${0##*/} [<interface>]

SYSNOPSIS:
  Configure the given interface (or the one passed by the networking stack
  environment variables) for DHCPv6:
   - disable StateLess Address AutoConfiguration (SLAAC)
   - disable Duplicate Address Detection (DAD)
   - enable Router Advertisements (RA) and Solicitations (RS)
   - disable temporary addresses
EOF

# Arguments
[ -n "${1}" ] && IFACE="${1}" && ADDRFAM='inet6' && METHOD='dhcp'
[ -z "${IFACE}" -o "${ADDRFAM}" != 'inet6' -o "${METHOD}" != 'dhcp' ] && exit 0

# BUG: Give the link time to come up
# REF: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783387
[ -z "${1}" ] && sleep 3

# IPv6 DHCPv6 address specific settings
#  - disable StateLess Address AutoConfiguration (SLAAC)
#  - disable Duplicate Address Detection (DAD)
#  - enable Router Advertisements (RA) and Solicitations (RS)
#  - disable temporary addresses
sysctl -q net.ipv6.conf.${IFACE}.autoconf=0
sysctl -q net.ipv6.conf.${IFACE}.accept_dad=0
sysctl -q net.ipv6.conf.${IFACE}.dad_transmits=0
sysctl -q net.ipv6.conf.${IFACE}.accept_ra=1
sysctl -q net.ipv6.conf.${IFACE}.accept_redirects=0
sysctl -q net.ipv6.conf.${IFACE}.router_solicitations=3
sysctl -q net.ipv6.conf.${IFACE}.use_tempaddr=0

