#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-apt-owncloud'

# Debconf
. /usr/share/debconf/confmodule
# ... preseed
for var_priority in owncloud-server:high owncloud-client:high; do
  var="${var_priority%:*}"
  priority="${var_priority#*:}"
  db_input ${priority} ${PKGNAME}/${var}
  db_go
done
# ... get
db_get ${PKGNAME}/owncloud-server && OWNCLOUD_SERVER="${RET}"
db_get ${PKGNAME}/owncloud-client && OWNCLOUD_CLIENT="${RET}"
db_stop

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Uninstall legacy files
if [ -e /etc/apt/sources.list.d/owncloud.list ]; then
  gcfg remove --batch --force /etc/apt/sources.list.d/owncloud.list
fi

# Fine-tune files
[ "${OWNCLOUD_SERVER}" == 'true' ] && gcfg.sed "s|^#deb |deb |" /etc/apt/sources.list.d/owncloud-server.list
[ "${OWNCLOUD_CLIENT}" == 'true' ] && gcfg.sed "s|^#deb |deb |" /etc/apt/sources.list.d/owncloud-client.list

# Exit
exit 0
