#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-root-env'

# Debconf
. /usr/share/debconf/confmodule
db_get custom-conf/host-type && HOST_TYPE="${RET}"
db_stop

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Fine-tune configuration
source /usr/share/custom-conf/custom-conf.defs
CUSTOM_ROOT_ENV_LOGOUT=
[ "${HOST_TYPE}" == 'vserver' ] && CUSTOM_ROOT_ENV_LOGOUT='# Clear history%NL;rm -f /root/.bash_history%NL;history -c'
gsed "s|%{CUSTOM_CONF_DOMAIN}|${CUSTOM_CONF_DOMAIN}|g;s|%{CUSTOM_ROOT_ENV_LOGOUT}|${CUSTOM_ROOT_ENV_LOGOUT}|g;s|%NL;|\n|g" /root/.bash{rc,_logout}

# Exit
exit 0

