#!/bin/sh
## CUSTOM-CONF: File automatically created/updated [custom-conf-network-qemu]

## QEMU/KVM bridge rules

# NAT enabled ?
# (Please use 'dpkg-reconfigure custom-conf-network-qemu' to change this setting)
%{CUSTOM_CONF_NETWORK_QEMU_ISNAT} || exit 0

# Masquerade (SNAT) outgoing traffic from bridge
"${IPTABLES}" --table nat --append POSTROUTING --source %{CUSTOM_CONF_NETWORK_QEMU_IPV4} ! --out-interface qemu --jump MASQUERADE

# DNAT incoming traffic to bridge
# (Example! Please use a separate file in the '/etc/iptables/rules.d/ipv4/nat.d' folder)
#"${IPTABLES}" --table nat --append PREROUTING --protocol tcp --dport 4567 --jump NAT --to-destination 192.168.215.123:4567

