#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-php5-apache2'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Fine-tune configuration
source /usr/share/custom-conf/custom-conf.defs
gsed "s|%{CUSTOM_CONF_SMTP_SERVER}|${CUSTOM_CONF_SMTP_SERVER}|g" /etc/php5/apache2/php.ini

# Fine-tune permissions
chmod 350 /var/log/php
chown www-data:adm /var/log/php

# Migrate former logs
if [ -e /var/log/apache2/php ]; then
  mv /var/log/apache2/php/* /var/log/php/.
  rmdir /var/log/apache2/php
fi

# Additional actions
invoke-rc.d apache2 restart

# Exit
exit 0

