#!/bin/bash
[ "${1}" != 'purge' ] && exit 0
PKGNAME='custom-conf-django'

# Uninstall files
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1
rm -rf /opt/django-1.11/* /etc/python/django /var/log/python/django /var/cache/python/django

# Exit
exit 0

