#!/bin/bash
# NOTE: see http://www.fifi.org/doc/debconf-doc/tutorial.html for how-to
[ "${1}" != 'configure' ] && exit 0

# Debconf
. /usr/share/debconf/confmodule
# ... preseed
for var_priority in host-type:high harddisk-type:high root-email:high; do
  var="${var_priority%:*}"
  priority="${var_priority#*:}"
  db_input ${priority} custom-conf/${var}
  db_go
done
db_stop

# Fix permissions
chmod 400 /usr/share/custom-conf/custom-conf.defs

# Exit
exit 0

