#!/bin/bash


## Usage
function __USAGE() {
cat << EOF
USAGE: ${0##*/} [-D <DPKG-directory>]

SYSNOPSIS:
  Cleanup all Flash NPAPI/PPAPI resources from the given Debian packaging
  directory.
EOF
}

# Arguments
DPKG_DIR=.
while [ -n "${1}" ]; do
  case "${1}" in
    '-h'|'--help')
      __USAGE
      exit 0
      ;;
    '-D'|'--debian')
      shift
      [ -z "${1}" ] && echo "ERROR: Missing option argument (<DPKG-directory>)" >&2 && exit 1
      DPKG_DIR="${1}"
      ;;
    *)
      echo "ERROR: Invalid option/argument (${1})" >&2 && __USAGE && exit 1
      ;;
  esac
  shift
done

# Validation
[ ! -d "${DPKG_DIR}/usr/lib/custom-pack-flash" ] && echo "ERROR: Invalid Debian packaging directory (${DPKG_DIR})" >&2 && exit 1


## Clean-up
find "${DPKG_DIR}/usr" -not -type d \( -path '*flash*' -o -name '*flash*' \) -not -name '.gitplaceholder' -delete
find "${DPKG_DIR}/usr" -type d -print0 | sort -zr | xargs -0 rmdir 2>/dev/null


## Done
exit 0

