#!/bin/bash
SCRIPT="${0##*/}"

## Usage
__USAGE() {
  cat <<EOF
USAGE: ${SCRIPT} [<options>] <zfs-src> [<zfs-src> ...]

SYSNOPSIS:
  Snapshot the given ZFS source dataset, automatically managing snapshot
  types (prefix) and retention factor.

OPTIONS:

  -T --type <prefix>
    Snapshot type/prefix; typically: hourly, daily, weekly, etc.

  -R --retention <factor>
    Quantity of snapshots to preserve for the given type/prefix

EOF
}
[ $# -lt 1 ] && __USAGE && exit 1

# Arguments
ZFS_SNAPSHOT_SRC_a=()
ZFS_SNAPSHOT_TYPE=
ZFS_SNAPSHOT_RETF=1
while [ -n "${1}" ]; do
  case "${1}" in
    'help'|'--help'|'-h')
      __USAGE
      exit 1
      ;;

    '-T'|'--type')
      [ -z "${2}" ] && echo "ERROR[${SCRIPT}]: Missing option argument (${1})" >&2 && exit 1
      ZFS_SNAPSHOT_TYPE="${2}"; shift
      ;;

    '-R'|'--retention')
      [ -z "${2}" ] && echo "ERROR[${SCRIPT}]: Missing option argument (${1})" >&2 && exit 1
      ZFS_SNAPSHOT_RETF="${2}"; shift
      ;;

    -*)
      echo "ERROR[${SCRIPT}]: Invalid option (${1})" >&2 && exit 1
      ;;

    *)
      ZFS_SNAPSHOT_SRC_a+=( "${1}" )
      ;;
  esac
  shift
done


## Check
[ -z "${ZFS_SNAPSHOT_TYPE}" ] && echo "ERROR[${SCRIPT}]: Snapshot type must be specified (--type)" >&2 && exit 1
[ "${ZFS_SNAPSHOT_RETF}" != '0' ] && [ "$(( ZFS_SNAPSHOT_RETF + 0 ))" != "${ZFS_SNAPSHOT_RETF}" ] && echo "ERROR[${SCRIPT}]: Retention factor must be integer (--retention)" >&2 && exit 1
[ "${ZFS_SNAPSHOT_RETF}" -lt 1 ] && echo "ERROR[${SCRIPT}]: Retention factor must be positive (--retention)" >&2 && exit 1


## Snapshot
ZFS_SNAPSHOT_TIMESTAMP="$(date +'%Y%m%dT%H%M%S')"

# Loop through sources
for ZFS_SNAPSHOT_SRC_i in "${!ZFS_SNAPSHOT_SRC_a[@]}"; do
  ZFS_SNAPSHOT_SRC="${ZFS_SNAPSHOT_SRC_a[${ZFS_SNAPSHOT_SRC_i}]}"

  # Create snapshot
  ZFS_SNAPSHOT_DST="${ZFS_SNAPSHOT_SRC}@${ZFS_SNAPSHOT_TIMESTAMP}-${ZFS_SNAPSHOT_TYPE}"
  if ! zfs snapshot -r "${ZFS_SNAPSHOT_DST}"; then
    echo "WARNING[${SCRIPT}]: Failed to perform snapshot (${ZFS_SNAPSHOT_DST})" >&2
    continue
  fi

  # Destroy unnecessary snaphots
  ZFS_SNAPSHOT_LIST="$(zfs list -Hp -t snapshot -r "${ZFS_SNAPSHOT_SRC}" | cut -f1 | grep -E "@[0-9]{8}T[0-9]{6}-${ZFS_SNAPSHOT_TYPE}\$" | sort)"
  for snapshot in $(echo "${ZFS_SNAPSHOT_LIST}" | head -n "-${ZFS_SNAPSHOT_RETF}"); do
    if ! zfs destroy "${snapshot}"; then
      echo "WARNING[${SCRIPT}]: Failed to destroy snapshot (${snapshot})" >&2
    fi
  done
done

# Done
exit 0
