#!/bin/bash
[ "${1}" != 'configure' ] && exit 0

## dh[begin]
#DEBHELPER#
## dh[end]

# Enable SysV if needs be
if [ ! -d /run/systemd/system -a -e /etc/init.d/zfs-mount ]; then
  update-rc.d zfs-mount-late defaults >/dev/null
fi

# Start service
invoke-rc.d zfs-mount-late start

# Exit
exit 0

