#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-conf-ipv6-dhcp'

# Uninstall files
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Additional action
echo "WARNING[${PKGNAME}]: Reboot to enforce changes!"

# Exit
exit 0

