#!/bin/bash


## Usage
function _help {
  cat << EOF
USAGE: ${0##*/}

SYNOPSIS:
  Clear (stop) IPv6 tables (firewall) rules gracefully.
  This script will NOT clear existing rules as long as ANY interface
  is still up.
EOF
}


## Actions
[ "${1##*-}" == 'help' ] && _help && exit 1
[ -n "${ADDRFAM}" -a "${ADDRFAM}" != 'inet6' ] && exit 0
[ ! -e /var/lock/ip6tables.lock ] && exit 0
[ -n "$(ifconfig | fgrep 'inet6 ')" ] && exit 0
ip6tables-control stop

