#!/bin/bash


## Usage
function _help {
  cat << EOF
USAGE: ${0##*/}

SYNOPSIS:
  Set (start) IPv4 tables (firewall) rules gracefully.
EOF
}


## Actions
[ "${1##*-}" == 'help' ] && _help && exit 1
[ -n "${ADDRFAM}" -a "${ADDRFAM}" != 'inet' ] && exit 0
[ -e /var/lock/iptables.lock ] && exit 0
iptables-control start

