#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-apt-nvidia-docker'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Message
cat << EOF
NOTICE[${PKGNAME}]: Please install the packages signing key MANUALLY
: wget https://nvidia.github.io/nvidia-docker/gpgkey -O- | apt-key add -
EOF

# Exit
exit 0

