#!/bin/sh
case "${DBUS_MEMBER}" in

  'Lock')
    # Destroy Kerberos 5 ticket
    kdestroy

    # Purge the SSH agent
    ssh-add -D
    ssh-add -e '/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so'
    # NOTE: Users with multiple PINs per card MUST use OpenSC "One PIN" alternative
    ssh-add -e '/usr/lib/x86_64-linux-gnu/onepin-opensc-pkcs11.so'
    ;;

  'Unlock')
    # Rename misnamed Kerberos 5 credential cache (ticket)
    # FIX: https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/1336663
    /etc/security/pam-script.d/krb5cc_rename "${USER}"

    # (Re-)Launch the smart card's event manager daemon
    if ! pgrep -U "${USER}" -c -x card_eventmgr >/dev/null; then
      UMASK="$(umask)"; umask 077
      card_eventmgr daemon pidfile="/tmp/.card_eventmgr${DISPLAY%%.*}.pid"
      umask ${UMASK}
    fi
    ;;

esac

