#!/bin/bash
## CUSTOM-CONF: File automatically created/updated [custom-conf-hostname-dhcp]

# Bail out if systemd is installed (let our sibling service do its job)
command -v systemctl >/dev/null && exit 0

# Update hostname
/usr/share/custom-conf-hostname-dhcp/scripts/update_hostname.sh

# Done
exit 0

