#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-nss-ldap'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Fine-tune configuration
source /usr/share/custom-conf/custom-conf.defs
if [ -n "${CUSTOM_CONF_NSS_BINDDN}" ]; then
  gcfg.sed "s|%{CUSTOM_CONF_NSS_SERVER_URI}|${CUSTOM_CONF_NSS_SERVER_URI}|g;s|%{CUSTOM_CONF_NSS_BASEDN}|${CUSTOM_CONF_NSS_BASEDN}|g;s|%{CUSTOM_CONF_NSS_BINDDN}|${CUSTOM_CONF_NSS_BINDDN}|g;s|%{CUSTOM_CONF_NSS_BINDPW}|${CUSTOM_CONF_NSS_BINDPW}|g;s|%{CUSTOM_CONF_NSS_USERDN}|${CUSTOM_CONF_NSS_USERDN}|g;s|%{CUSTOM_CONF_NSS_GROUPDN}|${CUSTOM_CONF_NSS_GROUPDN}|g" /etc/ldap.conf
else
  gcfg.sed "s|%{CUSTOM_CONF_NSS_SERVER_URI}|${CUSTOM_CONF_NSS_SERVER_URI}|g;s|%{CUSTOM_CONF_NSS_BASEDN}|${CUSTOM_CONF_NSS_BASEDN}|g;s|^binddn.*|#binddn n/a|g;s|^bindpw.*|#bindpw n/a|g;s|%{CUSTOM_CONF_NSS_USERDN}|${CUSTOM_CONF_NSS_USERDN}|g;s|%{CUSTOM_CONF_NSS_GROUPDN}|${CUSTOM_CONF_NSS_GROUPDN}|g" /etc/ldap.conf
fi
# ... nss_initgroups_ignoreusers
CUSTOM_CONF_NSS_IGNOREUSERS="$(cut -d: -f1 /etc/passwd | sort | tr '\n' ',' | sed 's|,$||')"
gcfg.sed "s|^nss_initgroups_ignoreusers.*|nss_initgroups_ignoreusers ${CUSTOM_CONF_NSS_IGNOREUSERS}|" /etc/ldap.conf

# Additional actions
if [ -e /etc/libnss-ldap.conf -a ! -h /etc/libnss-ldap.conf ]; then
  [ ! -e /etc/libnss-ldap.conf.debian ] && cp -p /etc/libnss-ldap.conf /etc/libnss-ldap.conf.debian
  rm -f /etc/libnss-ldap.conf
fi
if [ ! -e /etc/libnss-ldap.conf ]; then
  ln -s /etc/ldap.conf /etc/libnss-ldap.conf
fi
invoke-rc.d nscd restart

# Exit
exit 0

