#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-conf-nss-ldap'

# Preliminary actions
if [ -e /etc/libnss-ldap.conf.debian ]; then
  rm -f /etc/libnss-ldap.conf
  mv /etc/libnss-ldap.conf.debian /etc/libnss-ldap.conf
fi

# Uninstall files
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Exit
exit 0

