#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-blockdev]

## Usage
[ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/} <device>

HINT: echo 1 > /sys/block/<device>/device/delete
EOF

# Arguments
DEVICE="${1##*/}"


## Command
SYSDEV="/sys/block/${DEVICE}"
[ ! -e "${SYSDEV}" ] && echo "ERROR: Invalid block device (${SYSDEV})" >&2 && exit 1
echo 'CRITICAL: Make sure to umount all partitions on the device!'
for dev in ${SYSDEV}/device/block/sd*; do
  echo " > device: ${dev##*/}"
  for part in ${dev}/sd*; do
    echo " > partition: /dev/${part##*/}"
  done
done
echo 'PRESS <ENTER> TO CONTINUE OR <CTRL+C> TO ABORT...'
read
echo 1 > ${SYSDEV}/device/delete

