#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-blockdev]

# Usage
[ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/} <device>

HINT:    blockdev --rereadpt <device>
WARNING: Do NOT execute this command on a mounted device!
EOF

# Command
blockdev --rereadpt "$1"
echo 'Waiting for block device refresh'
sleep 3
ls -al /dev/disk/by-uuid | fgrep "${1##*/}"
ls -al /dev/disk/by-label | fgrep "${1##*/}"
