#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-blockdev]

## Usage
[ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/} <lun#>

HINT: echo 1 > /sys/class/scsi_device/0:0:0:<lun#>/device/delete
EOF

# Arguments
LUNID="${1}"


## Command
SYSDEV="/sys/class/scsi_device/0:0:0:${LUNID}"
[ ! -e "${SYSDEV}" ] && echo "ERROR: Invalid device/LUN (${SYSDEV})" >&2 && exit 1
echo 'CRITICAL: Make sure to umount all partitions on the device!'
for dev in ${SYSDEV}/device/block/sd*; do
  echo " > device: ${dev##*/}"
  for part in ${dev}/sd*; do
    echo " > partition: /dev/${part##*/}"
  done
done
echo 'PRESS <ENTER> TO CONTINUE OR <CTRL+C> TO ABORT...'
read
echo 1 > ${SYSDEV}/device/delete

