#!/bin/bash
## CUSTOM-UTIL: File automatically created/updated [custom-util-blockdev]

## Usage
[ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
USAGE: ${0##*/} <scsi-device>

HINT: echo 1 > /sys/class/scsi_device/<scsi-device>/device/delete
EOF

# Arguments
SCSI_DEVICE="${1}"


## Command
SCSI_CLASS="/sys/class/scsi_device/${SCSI_DEVICE}"
[ ! -e "${SCSI_CLASS}" ] && echo "ERROR: Invalid SCSI device (${SCSI_DEVICE}) <-> class (${SCSI_CLASS})" >&2 && exit 1
echo 'CRITICAL: Make sure to umount all partitions on the device!'
for dev in ${SCSI_CLASS}/device/block/sd*; do
  echo " > device: ${dev##*/}"
  for part in ${dev}/sd*; do
    echo " > partition: /dev/${part##*/}"
  done
done
echo 'PRESS <ENTER> TO CONTINUE OR <CTRL+C> TO ABORT...'
read
echo 1 > ${SCSI_CLASS}/device/delete

