#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-mdadm'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Fine-tune files
grep -q '^md.*raid[456]' /proc/mdstat && CUSTOM_CONF_MDADM_AUTOCHECK='true' || CUSTOM_CONF_MDADM_AUTOCHECK='false'
gsed "s|%{CUSTOM_CONF_MDADM_AUTOCHECK}|${CUSTOM_CONF_MDADM_AUTOCHECK}|g" /etc/default/mdadm

# Exit
exit 0

