#!/bin/sh
## CUSTOM-CONF: File automatically created/updated [custom-conf-docker]

# (Please use 'dpkg-reconfigure custom-conf-docker' to change this setting)
%{CUSTOM_CONF_DOCKER_IPTABLES_AUTO_EXIT}


## Docker-specific rules

# Inbound traffic (to containers published ports)
"${IPTABLES}" --table nat --new-chain DOCKER1_INBOUND
"${IPTABLES}" --table nat --append PREROUTING --match addrtype --dst-type LOCAL --jump DOCKER1_INBOUND
"${IPTABLES}" --table nat --append OUTPUT --match addrtype --dst-type LOCAL --jump DOCKER1_INBOUND
# (Please use a separate file to add containers-specific rules)
# "${IPTABLES}" --table nat --append DOCKER1_INBOUND \
#   --protocol <proto> \
#   --dport <port> \
#   --jump DNAT --to-destination <ip>:<port>

# Outbound traffic (from containers to the wide wild world)
"${IPTABLES}" --table nat --append POSTROUTING --out-interface docker1 --match addrtype --src-type LOCAL --jump MASQUERADE
"${IPTABLES}" --table nat --append POSTROUTING --source fec0:c0a8:d600::/120 ! --out-interface docker1 --jump MASQUERADE

# Internal traffic (between containers) using the "published" IP address (NAT loopback)
"${IPTABLES}" --table nat --append POSTROUTING --match mark --mark 0xC0A8D600 --jump MASQUERADE
# (Please use a separate file to add host-specific rules)
# "${IPTABLES}" --table mangle --append PREROUTING \
#   --in-interface docker1 \
#   --source fec0:c0a8:d600::/120 \
#   --destination <published-IP-address> \
#   --jump MARK --set-mark 0xC0A8D600

