#!/bin/sh
## CUSTOM-CONF: File automatically created/updated [custom-conf-lightdm]


## LightDM display setup script

# Shorten DPMS timeout on login screen
xset dpms 60 180 300

# Disable system beep
xset -b b off

# HACK: configure non-US keyboard in greeter (Launchpad #995715)
#setxkbmap ch fr

