#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-pack-base'

# Quirk: allow 'vim-tiny' to behave as 'vim'
# TODO: use dh_installalternatives
if ! update-alternatives --list vim | grep -qF vim.tiny ; then
  update-alternatives --install /usr/bin/vim vim /usr/bin/vim.tiny 0
fi

# Exit
exit 0

