#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-rsyslog-remote'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Fine-tune configuration
source /usr/share/custom-conf/custom-conf.defs
ipv6="$(ip -6 addr 2>/dev/null | fgrep 'scope global')"
server=
for s in ${CUSTOM_CONF_SYSLOG_SERVER}; do
  if [ -n "$(echo "${s}" | grep '^[:a-f0-9]*$')" ]; then
    [ -z "${ipv6}" ] && continue
    s="[${s}]"
  fi
  server="${s}"
  break
done
[ -n "${CUSTOM_CONF_SYSLOG_SERVER}" -a -z "${server}" ] && echo "ERROR[${PKGNAME}]: No IPv4 server found (${CUSTOM_CONF_SYSLOG_SERVER})" >&2
gcfg.sed "s|%{CUSTOM_CONF_SYSLOG_SERVER}|${server}|g" /etc/rsyslog.d/05-remote.conf

# Additional actions
invoke-rc.d rsyslog restart

# Exit
exit 0

