#!/bin/bash
# Ping the gateway (and make all network devices aware that we are alive)

# Ignore the local loopback interface
[ "${IFACE}" == 'lo' ] && exit 0

# Only run from on network 'up'
[ "${MODE}" != 'start' ] && exit 0

# Handle only IPv6
[ "${ADDRFAM}" != 'inet6' ] && exit 0

# Ping gateway
# NB: If DAD is enabled, now is too soon to have a valid gateway but DAD itself
#     will have advertised our becoming alive
sh -c "sleep 1; pinggw6 ${IFACE} -c 1 -W 1 >/dev/null" &

# Done
exit 0

