## CUSTOM-CONF: File automatically created/updated [custom-conf-symfony]

imports:
  - { resource: 'parameters.yml' }
  - { resource: 'security.yml' }

framework:
  #esi: ~
  secret: '%secret%'
  router:
    resource: '%kernel.project_dir%/app/config/routing.yml'
    strict_requirements: ~
  default_locale: '%locale%'
  translator: { fallbacks: ['%locale%'] }
  templating:
    engines: ['twig']
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  trusted_hosts: ~
  session:
    # (null; let PHP handles this as per PHP/Apache configuration)
    handler_id: ~
  fragments: ~
  http_method_override: true
  php_errors:
    # (false; let PHP handles this as per PHP/Apache configuration)
    log: false

# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
  debug: '%kernel.debug%'
  use_controller: false
  bundles: [ ]
  #java: /usr/bin/java
  filters:
    cssrewrite: ~
    #closure:
    #  jar: '%kernel.root_dir%/Resources/java/compiler.jar'
    #yui_css:
    #  jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'

# Doctrine Configuration
doctrine:
  dbal:
    driver:   '%database_driver%'
    host:     '%database_host%'
    port:     '%database_port%'
    dbname:   '%database_name%'
    user:     '%database_user%'
    password: '%database_password%'
    charset:  'UTF8'
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  transport: '%mailer_transport%'
  host:      '%mailer_host%'
  username:  '%mailer_user%'
  password:  '%mailer_password%'
  spool:     { type: 'memory' }

