#!/bin/sh
## CUSTOM-CONF: File automatically created/updated [custom-conf-docker]

# (Please use 'dpkg-reconfigure custom-conf-docker' to change this setting)
%{CUSTOM_CONF_DOCKER_IPTABLES_MANUAL_EXIT}

# Start Docker daemon
[ -e /var/run/iptables-control.hook.docker ] || exit 0
echo "WARNING: Docker daemon service MUST be restarted MANUALLY!" >&2
rm -f /var/run/iptables-control.hook.docker

