#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-conf-lightdm'

# Install files
custom-conf-install "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Warning
echo "WARNING[${PKGNAME}]: You MUST restart lightdm to enforce changes"
echo ": service lightdm restart"

# Exit
exit 0

