#!/bin/bash
[ "${1}" != 'configure' ] && exit 0
PKGNAME='custom-packages-install-flash'

# Update alternatives
update-alternatives --quiet --install \
  /usr/lib/mozilla/plugins/flash-mozilla.so \
  flash-mozilla.so \
  /usr/lib/custom-packages-install-flash/npapi/libflashplayer.so \
  50

# Exit
exit 0

