#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-packages-install-flash'

# Update alternatives
update-alternatives --quiet --remove \
  flash-mozilla.so \
  /usr/lib/custom-packages-install-flash/npapi/libflashplayer.so

# Exit
exit 0

