#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-conf-iptables'

# Disable IP tables
if [ -n "$(ifconfig | fgrep 'inet ')" ]; then
  iptables-control stop
fi
if [ -n "$(ifconfig | fgrep 'inet6 ')" ]; then
  ip6tables-control stop
fi

# Uninstall files
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Exit
exit 0

