#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-conf-pam-krb5_opensc'

# Preliminary actions
if [ -e /etc/pam_ldap.conf.debian ]; then
  rm -f /etc/pam_ldap.conf
  mv /etc/pam_ldap.conf.debian /etc/pam_ldap.conf
fi

# Uninstall files
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Exit
exit 0

