#!/bin/bash
[ "${1}" != 'remove' ] && exit 0
PKGNAME='custom-conf-motd'

# Uninstall files
custom-conf-uninstall "${PKGNAME}" "/usr/share/${PKGNAME}/config" || exit 1

# Additional actions
[ -d /etc/update-motd.d ] && chmod a+x /etc/update-motd.d/*

# Exit
exit 0

